In [8]:
print("Hello World!")

Hello World!


# NumPy

## 📦 1. O que é NumPy?

NumPy = **Numerical Python**. Ela introduz o objeto `ndarray` (N-dimensional array), que é:
- Mais eficiente que listas (em memória e velocidade)
- Vetorizado (operações em todo o array de uma vez)
- Base para álgebra linear, estatística, etc.

Para usar, importe com o alias padrão:


In [2]:
import numpy as np

## 🏗️ 2. Criando Arrays

### 2.1 `np.array()` – a partir de uma lista/tupla

In [11]:
# 1D (vetor)
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [ ]:
# 2D (matriz)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [13]:
# 3D (tensor)
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 2.2 `np.zeros()` – array preenchido com zeros

In [ ]:
# zero 1D com 5 elementos
z = np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


In [ ]:
# zero 2D (3 linhas, 4 colunas)
z2 = np.zeros((3, 4))
print(z2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 2.3 `np.ones()` – array preenchido com uns

In [17]:
o = np.ones((2, 3))
print(o)

[[1. 1. 1.]
 [1. 1. 1.]]


### 2.4 `np.arange()` – sequência numérica (similar ao `range()`)

In [20]:
# De 0 a 9 (step padrão = 1)
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# De 2 a 10 (exclusive), step 2
b = np.arange(2, 11, 2)
print(b)

[ 2  4  6  8 10]


In [ ]:
# Com floats
c = np.arange(0, 1, 0.2)
print(c)

[0.  0.2 0.4 0.6 0.8]


### 2.5 Bônus: `np.linspace()` – pontos igualmente espaçados

In [ ]:
# 5 pontos entre 0 e 10 (inclusive)
lin = np.linspace(0, 10, 5)
print(lin)

[ 0.   2.5  5.   7.5 10. ]


## 📐 3. Shape (Formato)

O **shape** é uma tupla que indica o número de elementos em cada dimensão.

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)  # (2, 3) → 2 linhas, 3 colunas

[[1 2 3]
 [4 5 6]]
(2, 3)


In [25]:
# Para 1D:
v = np.array([1, 2, 3])
print(v)
print(v.shape)    # (3,) → tupla com 1 elemento (atenção à vírgula!)

[1 2 3]
(3,)


In [ ]:
# Para escalar (0D):
# cria um array numpy com o número inteiro 42
# Como é passado apenas um número (escalar), o array resultante possui 0 dimensões, ou seja, um ponto no espaço matemático
s = np.array(42)
print(s)
print(s.shape)    # () → tupla vazia

42
()


### 📌 Regras importantes:

- **len(shape)** = número de dimensões (ndim)

- O produto dos elementos do shape = total de elementos (size)

In [5]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1.shape)  # (2,3)
print(arr1.ndim)   # 2
print(arr1.size)   # Quantidade de elementos do array/matriz: (6) ou (2*3) 

(2, 3)
2
6


### 🔄 Redimensionar (reshape)

- Método RESHAPE é utilizado para mudar a forma, isto é, reorganizar os elementos em uma nova estrutura de array/matriz

In [8]:
arr2 = np.arange(12)  # [0 1 2 ... 11] shape (12,)
print(arr2) # Exibe a organização do array
print(arr2.shape) # Exibe a quantidade de linhas e colunas (12 linhas, sem colunas/vazio)
print(arr2.ndim) # Exibe a quantidade de dimensões (1)
print(arr2.size) # Exibe a quantidade de elementos do array (12)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
1
12


In [11]:
# Transformar em 3x4
arr_3x4 = arr2.reshape(3, 4)
print(arr_3x4)# Exibe a nova organização do array
print(arr_3x4.shape)  # Exibe a quantidade de linhas e colunas (3 linhas, 4 colunas)
print(arr_3x4.ndim) # Exibe a quantidade de dimensões
print(arr_3x4.size) # Exibe a quantidade de elementos

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2
12


In [12]:
# Reshape/Transformar em 3 dimensões 2x2x3
# Reshape (bloco, linha, coluna)

arr_2x2x3 = arr2.reshape(2, 2, 3)
print(arr_2x2x3) # Exibe a nova organização do array
print(arr_2x2x3.shape)  # Exibe a quantidade de blocos (d1) x linhas (d2) x colunas (d3) (2, 2, 3)
print(arr_2x2x3.ndim) # Exibe a quantidade de dimensões
print(arr_2x2x3.size) # Exibe a quantidade de elementos

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
3
12


In [14]:
# RESHAPE com cálculo automático de linhas e colunas
# arr2.reshape(2, -1)
# arr2.reshape(2 linhas, calcule colunas)
# Usar -1 para inferir automaticamente
arr_auto = arr2.reshape(2, -1)
print(arr_auto) # Exibe a nova organização do array
print(arr_auto.shape)  # Exibe a quantidade de linhas (2) x colunas calculadas automaticamente (6)
print(arr_auto.ndim) # Exibe a quantidade de dimensões
print(arr_auto.size) # Exibe a quantidade de elementos

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)
2
12


## 🏷️ 4. dtype (Tipo de Dado)

O **dtype** define como os dados são armazenados na memória (inteiro, float, string, etc.).

- O Numpy infere automaticamente o dtype, mas pode ser forçado.


### 📌 Dtypes mais comuns:

| dtype | Descrição |
|-------|-----------|
| `int32`, `int64` | Inteiros com sinal |
| `uint8`, `uint16` | Inteiros sem sinal (0 a 255, etc) |
| `float32`, `float64` | Ponto flutuante |
| `bool` | Booleano (True/False) |
| `str` | String (menos eficiente) |
| `complex128` | Números complexos |

In [16]:
arr_int = np.array([1, 2, 3]) # array de inteiros
print(arr_int)
print(arr_int.dtype)

arr_float = np.array([1.0, 2.5, 3.7]) # array de float64
print(arr_float)
print(arr_float.dtype)

arr_forced = np.array([1, 2, 3], dtype=np.float32) # forçando tipo float32 em um array de inteiros
print(arr_forced)
print(arr_forced.dtype)


arr_mixed = np.array([1, 2, 3.5]) # Array de inteiros que se torna float se misturar
print(arr_mixed)
print(arr_mixed.dtype)  # float64 (por causa do 3.5)

[1 2 3]
int64
[1.  2.5 3.7]
float64
[1. 2. 3.]
float32
[1.  2.  3.5]
float64


### Especificando dtype nas funções de criação:

In [18]:
zeros_float = np.zeros(5, dtype=np.float32)
print(zeros_float)
print(zeros_float.dtype)
print()
ones_int = np.ones((2, 3), dtype=np.int8)
print(ones_int)
print(ones_int.dtype)
print()
arange_float = np.arange(0, 10, dtype=np.float64)
print(arange_float)
print(arange_float.dtype)

[0. 0. 0. 0. 0.]
float32

[[1 1 1]
 [1 1 1]]
int8

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


## 🧪 5. Exercícios Práticos

### Exercício 1: Crie os seguintes arrays:

In [27]:
# a) [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] (use zeros)

ex1 = np.zeros(10)
print(ex1)
print()

# b) [1, 1, 1, 1, 1, 1, 1, 1, 1, 1] (use ones)
ex2 = np.ones(10)
print(ex2)
print()

# c) [0, 2, 4, 6, 8, 10, 12, 14, 16, 18] (use arange)
ex3 = np.arange(0,19,2)
print(ex3)
print()

# d) Matriz 4x4 de uns (use ones com shape)
ex4 = np.ones((4,4))
print(ex4)
print()

# e) Matriz 3x2 preenchida com 7 (use full ou multiplicação)

print("Matriz 3x2 preenchida com 7 usando método np.full")
ex5 = np.full((3,2),7)
print(ex5)
print()

print("Matriz 3x2 preenchida com 1 e multiplicada por 7")
ex6 = np.ones((3,2))*7
print(ex6)
print()


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[ 0  2  4  6  8 10 12 14 16 18]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Matriz 3x2 preenchida com 7 usando método np.full
[[7 7]
 [7 7]
 [7 7]]

Matriz 3x2 preenchida com 1 e multiplicada por 7
[[7. 7.]
 [7. 7.]
 [7. 7.]]



### Exercício 2: Dado o array abaixo, responda:

```python
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
```

a) Qual o shape?  
b) Qual o dtype?  
c) Quantos elementos no total?  
d) Transforme em um array de 2 linhas e 6 colunas (reshape)  

In [34]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(f'O shape do array "arr" é: {arr.shape}')

print(f'O tipo de dados do array "arr" é: {arr.dtype}')

print(f'A quantidade de elementos do array "arr" é: {arr.size}')

arr_reshape = arr.reshape(2,6)
print(f'O shape do array "arr_reshape" é: {arr_reshape.shape}')

O shape do array "arr" é: (3, 4)
O tipo de dados do array "arr" é: int64
A quantidade de elementos do array "arr" é: 12
O shape do array "arr_reshape" é: (2, 6)


### Exercício 3: Qual a diferença entre:

```python
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3]])
```



---

In [36]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3]])

print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print()
print(b)
print(b.shape)
print(b.ndim)
print(b.size)

# RESPOSTA: 
# A variável "a" tem 1 linha e 0 coluna
# A variável "b" tem 1 linha com 3 colunas 

[1 2 3]
(3,)
1
3

[[1 2 3]]
(1, 3)
2
3



## 🧠 6. Dicas importantes

1. **Arrays vs Listas:**
   - Arrays são homogêneos (todos os elementos do mesmo tipo)
   - Se misturar tipos, NumPy faz *upcasting* (int → float → str)

2. **Cópia vs View:**
   - `reshape()` retorna uma *view* (não copia dados)
   - Use `.copy()` se precisar de uma cópia independente

3. **Performance:**
   - Operações com arrays são em C (muito mais rápidas que loops Python)

---



## 🎯 7. Desafio Final

Crie um array 3D com shape `(2, 3, 4)` onde:
- Todos os elementos sejam 5
- Depois, use `reshape` para transformá-lo em `(4, 6)`
- Verifique o dtype e o shape final

In [45]:
arr_teste = np.ones((2,3,4)) * 5
arr_teste2 = arr_teste.reshape(4,6)

print(arr_teste)
print()
print(arr_teste.shape)
print()
print(arr_teste.ndim)
print()
print(arr_teste.size)
print()
print(arr_teste2)
print()
print(arr_teste2.shape)
print()
print(arr_teste2.ndim)
print()
print(arr_teste2.size)

[[[5. 5. 5. 5.]
  [5. 5. 5. 5.]
  [5. 5. 5. 5.]]

 [[5. 5. 5. 5.]
  [5. 5. 5. 5.]
  [5. 5. 5. 5.]]]

(2, 3, 4)

3

24

[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]

(4, 6)

2

24


## 📚 8. Resumo

| Função | Criação | Exemplo |
|--------|---------|---------|
| `np.array()` | A partir de lista | `np.array([1,2,3])` |
| `np.zeros()` | Zeros | `np.zeros((2,3))` |
| `np.ones()` | Uns | `np.ones((4,))` |
| `np.arange()` | Sequência | `np.arange(0,10,2)` |
| `np.linspace()` | Intervalo | `np.linspace(0,1,5)` |

**Conceitos chave:**
- **shape**: tupla com dimensões
- **dtype**: tipo dos dados (int, float, etc.)
- **ndim**: número de dimensões
- **size**: total de elementos

---

## 🏠 Tarefa de Casa
1. Crie um array de 20 números ímpares entre 1 e 39 (use arange)
2. Transforme esse array em uma matriz 4x5
3. Crie uma matriz 3x3 de floats com valor 3.14 (use full)
4. Descubra o shape e dtype de cada um

Boa sorte! Na próxima aula, veremos operações matemáticas com arrays e indexação. 🚀

In [55]:
print(F'RESULTADOS:')
print()
print(f'Exercício 1:')
ex_casa1 = np.arange(1,41,2)
print(f'Os vinte elementos deste array são: {ex_casa1}')
print(f'O número de elementos deste array é: {ex_casa1.size}')
print()

print(f'Exercício 2:')
ex_casa2 = ex_casa1.reshape((4,5))
print(f'O shape deste array é:')
print(ex_casa2)
print()

print(f'Exercício 3:')
ex_casa3 = np.full()

RESULTADOS:

Exercício 1:
Os vinte elementos deste array são: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]
O número de elementos deste array é: 20

Exercício 2:
O shape deste array é:
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]]

